name: Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x86_64
            target: x86_64-linux
            os: ubuntu-latest
            test: true
          - name: Linux aarch64
            target: aarch64-linux
            os: ubuntu-latest
            test: false
          - name: Windows x86_64
            target: x86_64-windows
            os: windows-latest
            test: true
          - name: Windows aarch64
            target: aarch64-windows
            os: windows-latest
            test: false
          - name: macOS ARM64
            target: aarch64-macos
            os: macos-latest
            test: true

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.2

      - name: Build
        run: zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}

      - name: Test
        if: matrix.test
        run: zig build test -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MLz-${{ matrix.target }}
          path: zig-out/bin/*
